version: "3"

services:
    client:
        image: nginx
        ports:
            - "8080:80"
        volumes:
            - ./frontend:/etc/nginx/html
            - ./nginx/dev:/etc/nginx/conf.d
        network_mode: host